//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class AccountBalance
    {
        public Nullable<int> YDate { get; set; }
        public string sc { get; set; }
        public Nullable<int> Accountid { get; set; }
        public string Account { get; set; }
        public string Description { get; set; }
        public Nullable<int> Currencyid { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit1st { get; set; }
        public Nullable<decimal> Credit1st { get; set; }
        public Nullable<decimal> Debit2nd { get; set; }
        public Nullable<decimal> Credit2nd { get; set; }
    }
}
