//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class AdvancedSearch
    {
        public string type { get; set; }
        public Nullable<int> reference { get; set; }
        public Nullable<System.DateTime> jvdate { get; set; }
        public string sc { get; set; }
        public string Account { get; set; }
        public string AccountDescription { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public string Document { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount1st { get; set; }
        public Nullable<decimal> Amount2nd { get; set; }
        public string Dc { get; set; }
        public string Description { get; set; }
        public string Bank { get; set; }
        public string Details { get; set; }
        public Nullable<bool> Isposted { get; set; }
        public Nullable<decimal> Ratecurrency { get; set; }
        public int ID { get; set; }
    }
}
