//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bankreconciliation
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Jvdate { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public string Flag { get; set; }
        public string Dc { get; set; }
        public Nullable<bool> Ispassed { get; set; }
        public Nullable<bool> Isposted { get; set; }
        public Nullable<System.Guid> Rowguid { get; set; }
        public Nullable<int> Accountid { get; set; }
        public Nullable<int> Currencyid { get; set; }
        public Nullable<int> Vouchertypeid { get; set; }
        public Nullable<int> Voucherid { get; set; }
        public Nullable<int> SC { get; set; }
    }
}
