//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chartofaccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chartofaccount()
        {
            this.Chartofaccountsdetails = new ObservableListSource<Chartofaccountsdetail>();
            this.Journalchilds = new ObservableListSource<Journalchild>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Opendate { get; set; }
        public string Special { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Creationdate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> Modificationdate { get; set; }
        public Nullable<bool> isParent { get; set; }
        public Nullable<int> Currencyid { get; set; }
        public Nullable<int> Accountstatusid { get; set; }
        public Nullable<int> Accounttypeid { get; set; }
        public Nullable<int> Balancesheetid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Chartofaccountsdetail> Chartofaccountsdetails { get; set; }
        public virtual AccountStatu AccountStatu { get; set; }
        public virtual AccountType AccountType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Journalchild> Journalchilds { get; set; }
    }
}
