//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class CheckerCurrencies
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<decimal> Amount1st { get; set; }
        public Nullable<decimal> Amountr { get; set; }
        public Nullable<decimal> Amount2nd { get; set; }
        public Nullable<decimal> Amountf { get; set; }
        public Nullable<int> Line { get; set; }
    }
}
