//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class CheckerMaturity
    {
        public int ID { get; set; }
        public string Type { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
    }
}
