//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class ExchangeDifference
    {
        public Nullable<int> YDate { get; set; }
        public string Account { get; set; }
        public int AccountID { get; set; }
        public Nullable<int> Currencyid { get; set; }
        public string SC { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Balance1st { get; set; }
        public Nullable<decimal> Balance2nd { get; set; }
        public Nullable<decimal> Difference1st { get; set; }
        public Nullable<decimal> Difference2nd { get; set; }
    }
}
