//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public int ID { get; set; }
        public Nullable<int> Ydate { get; set; }
        public string Type { get; set; }
        public Nullable<int> Reference { get; set; }
        public string Branch { get; set; }
        public string Policy { get; set; }
        public string Endorsement { get; set; }
        public string Broker { get; set; }
        public string Insured { get; set; }
        public Nullable<int> Serial { get; set; }
        public Nullable<System.DateTime> Paydate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> Issuedate { get; set; }
        public Nullable<int> Sc { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Creationdate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> Modificationdate { get; set; }
    }
}
