//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journalchild
    {
        public int ID { get; set; }
        public Nullable<decimal> Ratecurrency { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public string Document { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Amount1st { get; set; }
        public Nullable<decimal> Amount2nd { get; set; }
        public string Dc { get; set; }
        public string Description { get; set; }
        public Nullable<int> Line { get; set; }
        public Nullable<bool> Isposted { get; set; }
        public Nullable<bool> Ispassed { get; set; }
        public string Recstamp { get; set; }
        public Nullable<int> Accountid { get; set; }
        public Nullable<int> Voucherid { get; set; }
        public Nullable<int> Currencyid { get; set; }
        public Nullable<int> Bankid { get; set; }
        public Nullable<int> Ydate { get; set; }
        public Nullable<int> Mdate { get; set; }
        public string AccountYearCurrency { get; set; }
    
        public virtual Journalparent Journalparent { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Chartofaccount Chartofaccount { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual TrialBalance1 TrialBalance { get; set; }
    }
}
