//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class JournalVouchers
    {
        public Nullable<System.DateTime> jvdate { get; set; }
        public string SC { get; set; }
        public string type { get; set; }
        public string TypeDescription { get; set; }
        public Nullable<int> reference { get; set; }
        public string Account { get; set; }
        public string AccountDescription { get; set; }
        public string description { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Dc { get; set; }
        public Nullable<decimal> Amount1st { get; set; }
        public Nullable<decimal> Amount2nd { get; set; }
        public Nullable<decimal> Rate2nd { get; set; }
        public Nullable<decimal> Ratecurrency { get; set; }
        public string Details { get; set; }
        public string CurrencyDescription { get; set; }
        public string Fromto { get; set; }
        public int ID { get; set; }
    }
}
