//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journalparent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journalparent()
        {
            this.Journalchilds = new ObservableListSource<Journalchild>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<System.DateTime> Jvdate { get; set; }
        public Nullable<decimal> Rate2nd { get; set; }
        public string Fromto { get; set; }
        public string Details { get; set; }
        public Nullable<bool> Isposted { get; set; }
        public Nullable<int> Vouchertypeid { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Creationdate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> Modificationdate { get; set; }
        public Nullable<int> YDate { get; set; }
        public Nullable<int> SC { get; set; }
        public Nullable<decimal> Instpay { get; set; }
    
        public virtual Vouchertype Vouchertype { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<Journalchild> Journalchilds { get; set; }
    }
}
