//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class NotesReceivables
    {
        public Nullable<int> ydate { get; set; }
        public string currency { get; set; }
        public string document { get; set; }
        public Nullable<System.DateTime> maturity { get; set; }
        public string account { get; set; }
        public string type { get; set; }
        public Nullable<System.DateTime> jvdate { get; set; }
        public Nullable<int> reference { get; set; }
        public string description { get; set; }
        public Nullable<decimal> debit { get; set; }
        public Nullable<decimal> credit { get; set; }
        public Nullable<decimal> debit1st { get; set; }
        public Nullable<decimal> credit1st { get; set; }
        public Nullable<decimal> debit2nd { get; set; }
        public Nullable<decimal> credit2nd { get; set; }
        public string SC { get; set; }
        public Nullable<int> ID { get; set; }
    }
}
