//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class PostDatedChequesDetailed
    {
        public string Account { get; set; }
        public Nullable<System.DateTime> Jvdate { get; set; }
        public Nullable<System.DateTime> Maturity { get; set; }
        public string Document { get; set; }
        public string Cur { get; set; }
        public string Bank { get; set; }
        public string Type { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<int> YDate { get; set; }
        public string Dc { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit1st { get; set; }
        public Nullable<decimal> Credit1st { get; set; }
        public Nullable<decimal> Debit2nd { get; set; }
        public Nullable<decimal> Credit2nd { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public string Sc { get; set; }
        public int JvID { get; set; }
    }
}
