//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounting
{
    using System;
    
    public partial class PostDatedChequesInstant
    {
        public Nullable<System.DateTime> Maturity { get; set; }
        public string Document { get; set; }
        public Nullable<int> asBank { get; set; }
        public string Account { get; set; }
        public Nullable<int> Description { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<decimal> Debit1st { get; set; }
        public Nullable<decimal> Credit1st { get; set; }
        public Nullable<decimal> Balance1st { get; set; }
        public Nullable<decimal> Debit2nd { get; set; }
        public Nullable<decimal> Credit2nd { get; set; }
        public Nullable<decimal> Balance2nd { get; set; }
        public string Type { get; set; }
        public Nullable<int> Reference { get; set; }
        public Nullable<int> Jvdate { get; set; }
        public Nullable<int> Ydate { get; set; }
        public string Sc { get; set; }
    }
}
