//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efControls.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.SubCompanies = new ObservableListSource<SubCompany>();
        }
    
        public int ID { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<int> FirstLocalCurrencyid { get; set; }
        public Nullable<int> SecondLocalCurrencyid { get; set; }
        public string RegisterNumber { get; set; }
        public string FiscalNumber { get; set; }
        public Nullable<bool> HasSubCompanies { get; set; }
        public Nullable<bool> isVisible { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<int> AccountLength { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Creationdate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> Modificationdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableListSource<SubCompany> SubCompanies { get; set; }
    }
}
