//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace efControls.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> FormID { get; set; }
        public Nullable<bool> Allowed { get; set; }
        public Nullable<bool> CanAdd { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanPrint { get; set; }
        public Nullable<int> CreatedByID { get; set; }
        public Nullable<System.DateTime> Creationdate { get; set; }
        public Nullable<int> ModifiedByID { get; set; }
        public Nullable<System.DateTime> Modificationdate { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual User User { get; set; }
    }
}
